export const styleSheet={
    container:{
        display:'flex',
        width:"100vw",
        height:"100vh",
        backgroundColor:"#E1DEDD",
        flexDirection:"column"
    },
    bodyContainer:{
        display:'flex',
        flexDirection:"column",
        width:"100%",
        height:"92%",
    },
    formContainer:{
        display:'flex',
        flexDirection:"column",
        width:"100%",
        height:"60%",
        alignItems:"center",
        justifyContent:"center"
    },
    txtFieldContainer:{
        display:'flex',
        flexDirection:"row",
        flexWrap:'wrap',
        width:"90%",
        height:"80%",
        alignItems:"center",
        justifyContent:'center'
    },
    txtFieldFirstThree:{
        width:"calc(100%/4*1)",
        marginLeft:"1%!important",
        marginRight:"1%!important",
        marginTop:"2%!important",
        marginBottom:"2%!important",
    },
    txtFieldLastTwo:{
        width:"calc(100%/2.6)",
        marginLeft:"1%!important",
        marginRight:"1%!important",
        marginTop:"2%!important",
        marginBottom:"2%!important",
    },
    btnContainer:{
        display:'flex',
        flexDirection:"column",
        width:"100%",
        height:"40%",
        alignItems:"center"
    },
    childContainerInBtn:{
        display:"flex",
        flexDirection:"row",
        width:"60%",
        height:"20%",
        alignItems:"center",
        justifyContent:"center",
    },
    btns:{
        width:"20%",
        marginLeft:"2%!important",
        marginRight:"2%!important",
    }

}