export const styleSheet={
    bodyContainer:{
        position:'absolute',
        display:'flex',
        flexDirection:"column",
        width:"100%",
        height:"100%",
    },
    formContainer:{
        display:'flex',
        flexDirection:"column",
        width:"100%",
        height:"35%",
        alignItems:"center",
        justifyContent:"center",
    },
    txtFieldContainer:{
        display:'flex',
        flexDirection:"row",
        flexWrap:'wrap',
        width:"100%",
        height:"80%",
        alignItems:"center",
        justifyContent:'center',
    },
    txtField:{
        position:'relative',
        display:"flex",
        width:"calc(100%/4)!important",
        marginLeft:"1%!important",
        marginRight:"1%!important",
        alignItems:"center",
        justifyContent:'center',
    },
    fieldContainer:{
        positon:'relative',
        width:'100%!important'
    },
    btnContainer:{
        display:'flex',
        flexDirection:"column",
        width:"100%",
        height:"10%",
        alignItems:"center",
        justifyContent:"center",
    },
    childContainerInBtn:{
        display:"flex",
        flexDirection:"row",
        width:"60%",
        height:"100%",
        alignItems:"center",
        justifyContent:"center",
    },
    btns:{
        width:"20%",
        marginLeft:"2%!important",
        marginRight:"2%!important",
    },
    tableContainer:{
        display:"flex",
        flexDirection:"column",
        heigth:'55%',
        width:"100%",
        alignItems:"center",
        justifyContent:"center",
    },
    tableChildContainer:{
        display:"flex",
        flexDirection:"column",
        width:"80%",
        alignItems:"center",
        justifyContent:"center",
    }

}